# Nome da Actions:  
name: Snake Game üêç

# Controlador do tempo que sera feito a atualiza√ß√£o dos arquivos.
on:
  schedule:
      # Ser√° atualizado a cada 5 horas.
    - cron: "0 */5 * * *"

# Permite executar na na lista de Actions (utilizado para testes de build).
  workflow_dispatch:

# Regras
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    # Checks repo under $GITHUB_WORKSHOP, so your job can access it
      - uses: actions/checkout@v4
      
      - name: Generate Snake Animation
    # Repositorio que ser√° utilizado para gerar os arquivos.
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: naah16
          # gif_out_path: dist/github-contribution-grid-snake.gif
          # svg_out_path: dist/github-contribution-grid-snake.svg
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake.gif

      # - run: git status

      # Para as atualiza√ß√µes.
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        # with:
        #   # the output branch we mentioned above
        #   target_branch: output
        #   build_dir: dist
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: dist
